@startuml Context
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

System(authsys, "Authorization System", "Manages the Authentication, API Access")
Person_Ext(covidtrackeruser, "Customers", "A customer of the Covid Tracker Solution")
Person(htuser, "Users", "High Tower genericuser")
System(covidtrackersys, "Covid Tracker System", "Allows customers to log, view test inforamtion and follow their lifecyle, regarding comunication to the authorities.")
System(coresys, "Core System", "Provides a central suite of systems, like notification, localization, etc")

System_Ext(mailgunAPI, "MailgunAPI", "API that enable you to send emails")

Rel(coresys, mailgunAPI, "Send e-mails")
Rel(authsys, coresys, "Consumes")
Rel(htuser, authsys, "Uses")
Rel(covidtrackeruser,htuser , "Extends")
Rel(covidtrackersys, coresys, "Consumes")
Rel(covidtrackeruser, covidtrackersys, "Uses")
@enduml
