name: Generate Docs

on:
  pull_request:
    types: [open, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Docs
        uses: clippings/c4builder-action@v1
      - uses: EndBug/add-and-commit@v7